package compiler

import (
	"fmt"
	"io"
	"strconv"
	"strings"
	"unicode"
)

// TypeScriptGenerator generates TypeScript definitions for Ella schemas
type TypeScriptGenerator struct {
	program       *Program
	enums         map[string]*DeclEnum
	models        map[string]*DeclModel
	nextErrorCode int // next error code to assign
}

// NewTypeScriptGenerator creates a new TypeScript code generator
func NewTypeScriptGenerator(program *Program) *TypeScriptGenerator {
	g := &TypeScriptGenerator{
		program:       program,
		enums:         make(map[string]*DeclEnum),
		models:        make(map[string]*DeclModel),
		nextErrorCode: 1000,
	}

	// Pre-process to collect enums and models for type resolution
	for _, node := range program.Nodes {
		switch n := node.(type) {
		case *DeclEnum:
			g.enums[n.Name.Name] = n
		case *DeclModel:
			g.models[n.Name.Name] = n
		}
	}

	return g
}

// GenerateToWriter writes the TypeScript definitions to the writer
func (g *TypeScriptGenerator) GenerateToWriter(w io.Writer) error {
	var sb strings.Builder

	// Write header
	sb.WriteString("// Auto-generated TypeScript definitions from Ella schema\n")
	sb.WriteString("// Do not edit this file directly\n\n")

	// Generate OptionArgs type for service methods
	g.generateOptionArgsType(&sb)

	// Generate constants
	for _, node := range g.program.Nodes {
		if c, ok := node.(*ConstDecl); ok {
			g.generateConst(&sb, c)
		}
	}

	// Generate enums
	for _, node := range g.program.Nodes {
		if e, ok := node.(*DeclEnum); ok {
			g.generateEnum(&sb, e)
		}
	}

	// Generate models (interfaces)
	for _, node := range g.program.Nodes {
		if m, ok := node.(*DeclModel); ok {
			g.generateModel(&sb, m)
		}
	}

	// Generate error types
	g.generateErrorTypes(&sb)

	// Generate service interfaces
	var services []*DeclService
	for _, node := range g.program.Nodes {
		if svc, ok := node.(*DeclService); ok {
			services = append(services, svc)
			g.generateServiceInterface(&sb, svc)
		}
	}

	// Generate the main Ella interface that wraps all services
	g.generateEllaInterface(&sb, services)

	// Generate global declaration
	g.generateGlobalDeclaration(&sb)

	_, err := w.Write([]byte(sb.String()))
	return err
}

// GenerateClientToWriter writes runtime TypeScript client code (.ts) to the writer.
func (g *TypeScriptGenerator) GenerateClientToWriter(w io.Writer) error {
	var sb strings.Builder

	sb.WriteString("// Auto-generated TypeScript client from Ella schema\n")
	sb.WriteString("// Do not edit this file directly\n\n")

	g.generateOptionArgsType(&sb)
	g.generateClientRuntimeTypes(&sb)

	for _, node := range g.program.Nodes {
		if c, ok := node.(*ConstDecl); ok {
			g.generateRuntimeConst(&sb, c)
		}
	}

	for _, node := range g.program.Nodes {
		if e, ok := node.(*DeclEnum); ok {
			g.generateRuntimeEnum(&sb, e)
		}
	}

	for _, node := range g.program.Nodes {
		if m, ok := node.(*DeclModel); ok {
			g.generateModel(&sb, m)
		}
	}

	g.generateClientErrorTypes(&sb)

	for _, node := range g.program.Nodes {
		if svc, ok := node.(*DeclService); ok {
			g.generateServiceInterface(&sb, svc)
			g.generateServiceFactory(&sb, svc)
		}
	}

	_, err := w.Write([]byte(sb.String()))
	return err
}

// GenerateRuntimeConstsToWriter writes runtime TypeScript exports.
// It emits schema const declarations and error code constants so values are available at runtime.
func (g *TypeScriptGenerator) GenerateRuntimeConstsToWriter(w io.Writer) error {
	var sb strings.Builder

	sb.WriteString("// Auto-generated TypeScript runtime constants from Ella schema\n")
	sb.WriteString("// Do not edit this file directly\n\n")

	for _, node := range g.program.Nodes {
		if c, ok := node.(*ConstDecl); ok {
			g.generateRuntimeConst(&sb, c)
		}
	}

	g.generateRuntimeErrors(&sb)

	_, err := w.Write([]byte(sb.String()))
	return err
}

// GenerateClient produces runtime TypeScript client source code.
func (g *TypeScriptGenerator) GenerateClient() (string, error) {
	var sb strings.Builder

	if err := g.GenerateClientToWriter(&sb); err != nil {
		return "", err
	}

	return sb.String(), nil
}

func (g *TypeScriptGenerator) generateOptionArgsType(sb *strings.Builder) {
	sb.WriteString("/**\n")
	sb.WriteString(" * Options for service method calls.\n")
	sb.WriteString(" */\n")
	sb.WriteString("export interface OptionArgs {\n")
	sb.WriteString("  /**\n")
	sb.WriteString("   * AbortSignal to cancel the request.\n")
	sb.WriteString("   */\n")
	sb.WriteString("  signal?: AbortSignal;\n")
	sb.WriteString("  /**\n")
	sb.WriteString("   * Cache key for caching the response.\n")
	sb.WriteString("   */\n")
	sb.WriteString("  cacheKey?: string;\n")
	sb.WriteString("  /**\n")
	sb.WriteString("   * Time-to-live for the cache entry (e.g., \"5m\", \"1h\").\n")
	sb.WriteString("   */\n")
	sb.WriteString("  cacheTTL?: string;\n")
	sb.WriteString("  /**\n")
	sb.WriteString("   * Timeout for the request (e.g., \"30s\", \"1m\"). Defaults to \"30s\".\n")
	sb.WriteString("   */\n")
	sb.WriteString("  timeout?: string;\n")
	sb.WriteString("}\n\n")
}

// Generate produces TypeScript definition source code
func (g *TypeScriptGenerator) Generate() (string, error) {
	var sb strings.Builder

	if err := g.GenerateToWriter(&sb); err != nil {
		return "", err
	}

	return sb.String(), nil
}

func (g *TypeScriptGenerator) generateConst(sb *strings.Builder, c *ConstDecl) {
	name := c.Assignment.Name.Name

	// Check if this is a template string with placeholders
	if strExpr, ok := c.Assignment.Value.(*ValueExprString); ok {
		strValue := strExpr.Token.Lit
		if hasTemplatePlaceholders(strValue) {
			// Generate function type
			matches := templatePlaceholderRegex.FindAllStringSubmatch(strValue, -1)
			seenParams := make(map[string]bool)
			var params []string
			for _, match := range matches {
				paramName := match[1]
				if !seenParams[paramName] {
					seenParams[paramName] = true
					params = append(params, paramName)
				}
			}

			sb.WriteString(fmt.Sprintf("export declare function %s(", name))
			for i, param := range params {
				if i > 0 {
					sb.WriteString(", ")
				}
				sb.WriteString(fmt.Sprintf("%s: string", param))
			}
			sb.WriteString("): string;\n\n")
			return
		}
	}

	// Regular constant
	value := g.exprToTSValue(c.Assignment.Value)
	sb.WriteString(fmt.Sprintf("export declare const %s: %s;\n\n", name, value))
}

func (g *TypeScriptGenerator) generateRuntimeConst(sb *strings.Builder, c *ConstDecl) {
	name := c.Assignment.Name.Name

	if strExpr, ok := c.Assignment.Value.(*ValueExprString); ok {
		strValue := strExpr.Token.Lit
		if hasTemplatePlaceholders(strValue) {
			matches := templatePlaceholderRegex.FindAllStringSubmatch(strValue, -1)
			seenParams := make(map[string]bool)
			var params []string
			for _, match := range matches {
				paramName := match[1]
				if !seenParams[paramName] {
					seenParams[paramName] = true
					params = append(params, paramName)
				}
			}

			sb.WriteString(fmt.Sprintf("export function %s(", name))
			for i, param := range params {
				if i > 0 {
					sb.WriteString(", ")
				}
				sb.WriteString(fmt.Sprintf("%s: string", param))
			}
			sb.WriteString("): string {\n")
			sb.WriteString(fmt.Sprintf("  return %s;\n", toTemplateLiteral(strValue)))
			sb.WriteString("}\n\n")
			return
		}
	}

	value := g.exprToTSValue(c.Assignment.Value)
	sb.WriteString(fmt.Sprintf("export const %s = %s;\n\n", name, value))
}

func (g *TypeScriptGenerator) generateRuntimeErrors(sb *strings.Builder) {
	nextErrorCode := 1000
	hasErrors := false

	for _, node := range g.program.Nodes {
		if e, ok := node.(*DeclError); ok {
			hasErrors = true

			var errorCode int
			if e.Code != nil {
				code, _ := strconv.Atoi(e.Code.Token.Lit)
				errorCode = code
			} else {
				errorCode = nextErrorCode
				nextErrorCode++
			}

			sb.WriteString(fmt.Sprintf("export const %s = %d;\n", e.Name.Name, errorCode))
		}
	}

	if hasErrors {
		sb.WriteString("\n")
	}
}

func (g *TypeScriptGenerator) generateRuntimeEnum(sb *strings.Builder, e *DeclEnum) {
	enumName := e.Name.Name
	isStringEnum := g.isStringEnum(e)

	sb.WriteString(fmt.Sprintf("export type %s =\n", enumName))

	first := true
	for _, v := range e.Values {
		if v.Name.Name == "_" {
			continue
		}

		var value string
		if isStringEnum && v.IsDefined {
			if strVal, ok := v.Value.(*ValueExprString); ok {
				value = fmt.Sprintf(`"%s"`, strVal.Token.Lit)
			} else {
				value = fmt.Sprintf(`"%s"`, v.Name.Name)
			}
		} else {
			value = fmt.Sprintf(`"%s"`, v.Name.Name)
		}

		if !first {
			sb.WriteString(" |\n")
		}
		sb.WriteString(fmt.Sprintf("  %s", value))
		first = false
	}
	sb.WriteString(";\n\n")

	sb.WriteString(fmt.Sprintf("export const %sValues = {\n", enumName))
	for _, v := range e.Values {
		if v.Name.Name == "_" {
			continue
		}
		var value string
		if isStringEnum && v.IsDefined {
			if strVal, ok := v.Value.(*ValueExprString); ok {
				value = fmt.Sprintf(`"%s"`, strVal.Token.Lit)
			} else {
				value = fmt.Sprintf(`"%s"`, v.Name.Name)
			}
		} else {
			value = fmt.Sprintf(`"%s"`, v.Name.Name)
		}
		sb.WriteString(fmt.Sprintf("  %s: %s,\n", v.Name.Name, value))
	}
	sb.WriteString("} as const;\n\n")
}

func (g *TypeScriptGenerator) generateClientRuntimeTypes(sb *strings.Builder) {
	sb.WriteString("export interface EllaRpcConnection {\n")
	sb.WriteString("  request<TResult>(method: string, params?: unknown, options?: OptionArgs): Promise<TResult>;\n")
	sb.WriteString("}\n\n")

	sb.WriteString("export interface FetchJsonRpcOptions {\n")
	sb.WriteString("  fetcher?: typeof fetch;\n")
	sb.WriteString("  headers?: Record<string, string>;\n")
	sb.WriteString("  withTrace?: boolean;\n")
	sb.WriteString("}\n\n")

	sb.WriteString("export class EllaRPCError extends Error {\n")
	sb.WriteString("  readonly code: number;\n")
	sb.WriteString("  readonly cause?: string;\n\n")
	sb.WriteString("  constructor(code: number, message: string, cause?: string) {\n")
	sb.WriteString("    super(message);\n")
	sb.WriteString("    this.name = \"EllaRPCError\";\n")
	sb.WriteString("    this.code = code;\n")
	sb.WriteString("    this.cause = cause;\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n\n")

	sb.WriteString("export function isEllaRPCError(err: unknown): err is EllaRPCError {\n")
	sb.WriteString("  return err instanceof EllaRPCError;\n")
	sb.WriteString("}\n\n")

	sb.WriteString("let ellaRpcRequestId = 0;\n\n")

	sb.WriteString("function parseDurationToMs(value?: string): number | undefined {\n")
	sb.WriteString("  if (!value) {\n")
	sb.WriteString("    return undefined;\n")
	sb.WriteString("  }\n")
	sb.WriteString("  const match = /^([0-9]+)(ms|s|m|h)$/.exec(value.trim());\n")
	sb.WriteString("  if (!match) {\n")
	sb.WriteString("    return undefined;\n")
	sb.WriteString("  }\n")
	sb.WriteString("  const amount = Number(match[1]);\n")
	sb.WriteString("  const unit = match[2];\n")
	sb.WriteString("  switch (unit) {\n")
	sb.WriteString("    case \"ms\":\n")
	sb.WriteString("      return amount;\n")
	sb.WriteString("    case \"s\":\n")
	sb.WriteString("      return amount * 1000;\n")
	sb.WriteString("    case \"m\":\n")
	sb.WriteString("      return amount * 60 * 1000;\n")
	sb.WriteString("    case \"h\":\n")
	sb.WriteString("      return amount * 60 * 60 * 1000;\n")
	sb.WriteString("    default:\n")
	sb.WriteString("      return undefined;\n")
	sb.WriteString("  }\n")
	sb.WriteString("}\n\n")

	sb.WriteString("function withTimeout(signal: AbortSignal | undefined, timeout?: string): AbortSignal | undefined {\n")
	sb.WriteString("  const timeoutMs = parseDurationToMs(timeout);\n")
	sb.WriteString("  if (timeoutMs == null) {\n")
	sb.WriteString("    return signal;\n")
	sb.WriteString("  }\n")
	sb.WriteString("  const timeoutSignal = AbortSignal.timeout(timeoutMs);\n")
	sb.WriteString("  if (!signal) {\n")
	sb.WriteString("    return timeoutSignal;\n")
	sb.WriteString("  }\n")
	sb.WriteString("  return AbortSignal.any([signal, timeoutSignal]);\n")
	sb.WriteString("}\n\n")

	sb.WriteString("function withTraceHost(host: string, method: string, withTrace?: boolean): string {\n")
	sb.WriteString("  if (!withTrace) {\n")
	sb.WriteString("    return host;\n")
	sb.WriteString("  }\n")
	sb.WriteString("  const url = new URL(host);\n")
	sb.WriteString("  url.searchParams.append(\"ella_t\", method);\n")
	sb.WriteString("  return url.toString();\n")
	sb.WriteString("}\n\n")

	sb.WriteString("export function createFetchJsonRpc(host: string, options: FetchJsonRpcOptions = {}): EllaRpcConnection {\n")
	sb.WriteString("  const fetcher = options.fetcher ?? fetch;\n")
	sb.WriteString("  const baseHeaders = options.headers ?? {};\n\n")
	sb.WriteString("  return {\n")
	sb.WriteString("    async request<TResult>(method: string, params?: unknown, callOptions?: OptionArgs): Promise<TResult> {\n")
	sb.WriteString("      const id = ++ellaRpcRequestId;\n")
	sb.WriteString("      const requestPayload = [{\n")
	sb.WriteString("        jsonrpc: \"2.0\",\n")
	sb.WriteString("        method,\n")
	sb.WriteString("        params,\n")
	sb.WriteString("        id,\n")
	sb.WriteString("      }];\n\n")
	sb.WriteString("      const endpoint = withTraceHost(host, method, options.withTrace);\n")
	sb.WriteString("      const response = await fetcher(endpoint, {\n")
	sb.WriteString("        method: \"POST\",\n")
	sb.WriteString("        headers: {\n")
	sb.WriteString("          \"Content-Type\": \"application/json\",\n")
	sb.WriteString("          \"Accept\": \"application/json\",\n")
	sb.WriteString("          ...baseHeaders,\n")
	sb.WriteString("        },\n")
	sb.WriteString("        body: JSON.stringify(requestPayload),\n")
	sb.WriteString("        signal: withTimeout(callOptions?.signal, callOptions?.timeout),\n")
	sb.WriteString("      });\n\n")
	sb.WriteString("      if (!response.ok) {\n")
	sb.WriteString("        throw new EllaRPCError(-32603, `unexpected HTTP status ${response.status}`);\n")
	sb.WriteString("      }\n\n")
	sb.WriteString("      if (response.status === 204) {\n")
	sb.WriteString("        throw new EllaRPCError(-32603, \"missing JSON-RPC response body\");\n")
	sb.WriteString("      }\n\n")
	sb.WriteString("      const text = await response.text();\n")
	sb.WriteString("      if (!text.trim()) {\n")
	sb.WriteString("        throw new EllaRPCError(-32603, \"empty JSON-RPC response body\");\n")
	sb.WriteString("      }\n\n")
	sb.WriteString("      const payload = JSON.parse(text) as unknown;\n")
	sb.WriteString("      const raw = Array.isArray(payload) ? payload[0] : payload;\n")
	sb.WriteString("      if (!raw || typeof raw !== \"object\") {\n")
	sb.WriteString("        throw new EllaRPCError(-32603, \"invalid JSON-RPC response payload\");\n")
	sb.WriteString("      }\n\n")
	sb.WriteString("      const rpc = raw as {\n")
	sb.WriteString("        jsonrpc?: string;\n")
	sb.WriteString("        result?: TResult;\n")
	sb.WriteString("        error?: { code?: number; message?: string; cause?: string };\n")
	sb.WriteString("      };\n")
	sb.WriteString("      if (rpc.jsonrpc !== \"2.0\") {\n")
	sb.WriteString("        throw new EllaRPCError(-32600, \"invalid JSON-RPC version\");\n")
	sb.WriteString("      }\n")
	sb.WriteString("      if (rpc.error) {\n")
	sb.WriteString("        throw new EllaRPCError(\n")
	sb.WriteString("          rpc.error.code ?? -32603,\n")
	sb.WriteString("          rpc.error.message ?? \"internal error\",\n")
	sb.WriteString("          rpc.error.cause,\n")
	sb.WriteString("        );\n")
	sb.WriteString("      }\n\n")
	sb.WriteString("      return rpc.result as TResult;\n")
	sb.WriteString("    },\n")
	sb.WriteString("  };\n")
	sb.WriteString("}\n\n")
}

func (g *TypeScriptGenerator) generateClientErrorTypes(sb *strings.Builder) {
	hasErrors := false
	nextErrorCode := 1000

	for _, node := range g.program.Nodes {
		e, ok := node.(*DeclError)
		if !ok {
			continue
		}
		hasErrors = true

		var errorCode int
		if e.Code != nil {
			code, _ := strconv.Atoi(e.Code.Token.Lit)
			errorCode = code
		} else {
			errorCode = nextErrorCode
			nextErrorCode++
		}

		sb.WriteString(fmt.Sprintf("export const %s = %d;\n", e.Name.Name, errorCode))
		sb.WriteString(fmt.Sprintf("export function is%s(err: unknown): err is EllaRPCError {\n", e.Name.Name))
		sb.WriteString(fmt.Sprintf("  return isEllaRPCError(err) && err.code === %s;\n", e.Name.Name))
		sb.WriteString("}\n\n")
	}

	if hasErrors {
		sb.WriteString("\n")
	}
}

func (g *TypeScriptGenerator) generateServiceFactory(sb *strings.Builder, svc *DeclService) {
	svcName := svc.Name.Name
	sb.WriteString(fmt.Sprintf("export function create%s(conn: EllaRpcConnection): %s {\n", svcName, svcName))
	sb.WriteString("  return {\n")

	for _, method := range svc.Methods {
		g.generateServiceFactoryMethod(sb, svc, method)
	}

	sb.WriteString("  };\n")
	sb.WriteString("}\n\n")
}

func (g *TypeScriptGenerator) generateServiceFactoryMethod(sb *strings.Builder, svc *DeclService, method *DeclServiceMethod) {
	methodName := tsToCamelCase(method.Name.Name)
	sb.WriteString(fmt.Sprintf("    async %s(", methodName))

	for i, arg := range method.Args {
		if i > 0 {
			sb.WriteString(", ")
		}
		argName := tsToCamelCase(arg.Name.Name)
		argType := g.declTypeToTSType(arg.Type)
		sb.WriteString(fmt.Sprintf("%s: %s", argName, argType))
	}
	if len(method.Args) > 0 {
		sb.WriteString(", ")
	}
	sb.WriteString("options?: OptionArgs")

	sb.WriteString("): Promise<")
	if len(method.Returns) == 0 {
		sb.WriteString("void")
	} else if len(method.Returns) == 1 {
		sb.WriteString(g.declTypeToTSType(method.Returns[0].Type))
	} else {
		sb.WriteString("{ ")
		for i, ret := range method.Returns {
			if i > 0 {
				sb.WriteString("; ")
			}
			sb.WriteString(fmt.Sprintf("%s: %s", tsToCamelCase(ret.Name.Name), g.declTypeToTSType(ret.Type)))
		}
		sb.WriteString(" }")
	}
	sb.WriteString("> {\n")

	if len(method.Args) > 0 {
		sb.WriteString("      const params = {\n")
		for _, arg := range method.Args {
			argName := tsToCamelCase(arg.Name.Name)
			sb.WriteString(fmt.Sprintf("        %s,\n", argName))
		}
		sb.WriteString("      };\n")
	}

	rpcMethod := fmt.Sprintf("%s.%s", svc.Name.Name, method.Name.Name)

	if len(method.Returns) == 0 {
		if len(method.Args) > 0 {
			sb.WriteString(fmt.Sprintf("      await conn.request<unknown>(\"%s\", params, options);\n", rpcMethod))
		} else {
			sb.WriteString(fmt.Sprintf("      await conn.request<unknown>(\"%s\", undefined, options);\n", rpcMethod))
		}
		sb.WriteString("      return;\n")
		sb.WriteString("    },\n")
		return
	}

	if len(method.Returns) == 1 {
		retName := tsToCamelCase(method.Returns[0].Name.Name)
		retType := g.declTypeToTSType(method.Returns[0].Type)
		if len(method.Args) > 0 {
			sb.WriteString(fmt.Sprintf("      const result = await conn.request<{ %s: %s }>(\"%s\", params, options);\n", retName, retType, rpcMethod))
		} else {
			sb.WriteString(fmt.Sprintf("      const result = await conn.request<{ %s: %s }>(\"%s\", undefined, options);\n", retName, retType, rpcMethod))
		}
		sb.WriteString(fmt.Sprintf("      return result.%s;\n", retName))
		sb.WriteString("    },\n")
		return
	}

	sb.WriteString("      type MethodOutput = {\n")
	for _, ret := range method.Returns {
		retName := tsToCamelCase(ret.Name.Name)
		retType := g.declTypeToTSType(ret.Type)
		sb.WriteString(fmt.Sprintf("        %s: %s;\n", retName, retType))
	}
	sb.WriteString("      };\n")

	if len(method.Args) > 0 {
		sb.WriteString(fmt.Sprintf("      return conn.request<MethodOutput>(\"%s\", params, options);\n", rpcMethod))
	} else {
		sb.WriteString(fmt.Sprintf("      return conn.request<MethodOutput>(\"%s\", undefined, options);\n", rpcMethod))
	}
	sb.WriteString("    },\n")
}

func toTemplateLiteral(s string) string {
	template := strings.ReplaceAll(s, "`", "\\`")
	template = strings.ReplaceAll(template, "${", "\\${")
	template = templatePlaceholderRegex.ReplaceAllString(template, "${$1}")
	return fmt.Sprintf("`%s`", template)
}

func (g *TypeScriptGenerator) exprToTSValue(expr Expr) string {
	switch e := expr.(type) {
	case *ValueExprString:
		return fmt.Sprintf(`"%s"`, e.Token.Lit)
	case *ValueExprNumber:
		return e.Token.Lit
	case *ValueExprBool:
		return e.Token.Lit
	case *ValueExprNull:
		return "null"
	case *IdenExpr:
		return e.Name
	default:
		return "unknown"
	}
}

func (g *TypeScriptGenerator) generateEnum(sb *strings.Builder, e *DeclEnum) {
	enumName := e.Name.Name
	isStringEnum := g.isStringEnum(e)

	sb.WriteString(fmt.Sprintf("export type %s =\n", enumName))

	for i, v := range e.Values {
		if v.Name.Name == "_" {
			continue
		}

		var value string
		if isStringEnum && v.IsDefined {
			if strVal, ok := v.Value.(*ValueExprString); ok {
				value = fmt.Sprintf(`"%s"`, strVal.Token.Lit)
			} else {
				value = fmt.Sprintf(`"%s"`, v.Name.Name)
			}
		} else {
			value = fmt.Sprintf(`"%s"`, v.Name.Name)
		}

		if i > 0 {
			sb.WriteString(" |\n")
		}
		sb.WriteString(fmt.Sprintf("  %s", value))
	}
	sb.WriteString(";\n\n")

	// Generate enum constant object for runtime access
	sb.WriteString(fmt.Sprintf("export declare const %sValues: {\n", enumName))
	for _, v := range e.Values {
		if v.Name.Name == "_" {
			continue
		}
		var value string
		if isStringEnum && v.IsDefined {
			if strVal, ok := v.Value.(*ValueExprString); ok {
				value = fmt.Sprintf(`"%s"`, strVal.Token.Lit)
			} else {
				value = fmt.Sprintf(`"%s"`, v.Name.Name)
			}
		} else {
			value = fmt.Sprintf(`"%s"`, v.Name.Name)
		}
		sb.WriteString(fmt.Sprintf("  readonly %s: %s;\n", v.Name.Name, value))
	}
	sb.WriteString("};\n\n")
}

func (g *TypeScriptGenerator) isStringEnum(e *DeclEnum) bool {
	for _, v := range e.Values {
		if v.IsDefined {
			if _, ok := v.Value.(*ValueExprString); ok {
				return true
			}
		}
	}
	return false
}

func (g *TypeScriptGenerator) generateModel(sb *strings.Builder, m *DeclModel) {
	modelName := m.Name.Name

	sb.WriteString(fmt.Sprintf("export interface %s", modelName))

	// Handle extends
	if len(m.Extends) > 0 {
		sb.WriteString(" extends ")
		for i, ext := range m.Extends {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(ext.Name)
		}
	}

	sb.WriteString(" {\n")

	for _, f := range m.Fields {
		fieldName := tsToCamelCase(f.Name.Name)
		fieldType := g.declTypeToTSType(f.Type)
		sb.WriteString(fmt.Sprintf("  %s: %s;\n", fieldName, fieldType))
	}

	sb.WriteString("}\n\n")
}

func (g *TypeScriptGenerator) declTypeToTSType(t DeclType) string {
	switch dt := t.(type) {
	case *DeclStringType:
		return "string"
	case *DeclNumberType:
		return "number"
	case *DeclBoolType:
		return "boolean"
	case *DeclByteType:
		return "number"
	case *DeclAnyType:
		return "any"
	case *DeclTimestampType:
		return "string"
	case *DeclArrayType:
		elemType := g.declTypeToTSType(dt.Type.(DeclType))
		return elemType + "[]"
	case *DeclMapType:
		keyType := g.declTypeToTSType(dt.KeyType.(DeclType))
		valueType := g.declTypeToTSType(dt.ValueType.(DeclType))
		if keyType == "string" {
			return fmt.Sprintf("Record<%s, %s>", keyType, valueType)
		}
		return fmt.Sprintf("Map<%s, %s>", keyType, valueType)
	case *DeclCustomType:
		return dt.Name.Name
	default:
		return "unknown"
	}
}

func (g *TypeScriptGenerator) generateErrorTypes(sb *strings.Builder) {
	hasErrors := false
	for _, node := range g.program.Nodes {
		if _, ok := node.(*DeclError); ok {
			hasErrors = true
			break
		}
	}

	if !hasErrors {
		return
	}

	sb.WriteString("// Error types\n")
	sb.WriteString("export interface EllaError {\n")
	sb.WriteString("  code: number;\n")
	sb.WriteString("  message: string;\n")
	sb.WriteString("  cause?: string;\n")
	sb.WriteString("}\n\n")

	// Generate individual error constants
	for _, node := range g.program.Nodes {
		if e, ok := node.(*DeclError); ok {

			var errorCode int
			if e.Code != nil {
				code, _ := strconv.Atoi(e.Code.Token.Lit)
				errorCode = code
			} else {
				errorCode = g.nextErrorCode
				g.nextErrorCode++
			}

			sb.WriteString(fmt.Sprintf("export declare const %s = %d;\n", e.Name.Name, errorCode))
		}
	}
	sb.WriteString("\n")
}

func (g *TypeScriptGenerator) generateServiceInterface(sb *strings.Builder, svc *DeclService) {
	svcName := svc.Name.Name

	sb.WriteString(fmt.Sprintf("export interface %s {\n", svcName))

	for _, method := range svc.Methods {
		g.generateMethodSignature(sb, method)
	}

	sb.WriteString("}\n\n")
}

func (g *TypeScriptGenerator) generateMethodSignature(sb *strings.Builder, method *DeclServiceMethod) {
	methodName := tsToCamelCase(method.Name.Name)

	sb.WriteString(fmt.Sprintf("  %s(", methodName))

	// Parameters
	for i, arg := range method.Args {
		if i > 0 {
			sb.WriteString(", ")
		}
		argName := tsToCamelCase(arg.Name.Name)
		argType := g.declTypeToTSType(arg.Type)
		sb.WriteString(fmt.Sprintf("%s: %s", argName, argType))
	}

	// Add optional options parameter
	if len(method.Args) > 0 {
		sb.WriteString(", ")
	}
	sb.WriteString("options?: OptionArgs")

	sb.WriteString("): Promise<")

	// Return type
	if len(method.Returns) == 0 {
		sb.WriteString("void")
	} else if len(method.Returns) == 1 {
		ret := method.Returns[0]
		retType := g.declTypeToTSType(ret.Type)
		sb.WriteString(retType)
	} else {
		// Multiple returns - create inline object type
		sb.WriteString("{ ")
		for i, ret := range method.Returns {
			if i > 0 {
				sb.WriteString("; ")
			}
			retName := tsToCamelCase(ret.Name.Name)
			retType := g.declTypeToTSType(ret.Type)
			sb.WriteString(fmt.Sprintf("%s: %s", retName, retType))
		}
		sb.WriteString(" }")
	}

	sb.WriteString(">;\n")
}

func (g *TypeScriptGenerator) generateEllaInterface(sb *strings.Builder, services []*DeclService) {
	sb.WriteString("// Main Ella interface - the global object exposed by WASM\n")
	sb.WriteString("export interface Ella {\n")
	sb.WriteString("  /**\n")
	sb.WriteString("   * Create and register an HTTP caller with the API host and optional headers.\n")
	sb.WriteString("   * @param host - The API endpoint URL (e.g., \"https://api.example.com\")\n")
	sb.WriteString("   * @param withTrace - Optional: attach method names to the URL\n")
	sb.WriteString("   * @param headers - Optional headers to include in all requests\n")
	sb.WriteString("   * @returns caller handler ID used by create<Service>Client methods\n")
	sb.WriteString("   */\n")
	sb.WriteString("  createHttpCaller(host: string, withTrace?: boolean, headers?: Record<string, string>): number;\n\n")

	sb.WriteString("  /**\n")
	sb.WriteString("   * Invalidate a specific cache entry by key.\n")
	sb.WriteString("   * @param key - The cache key to invalidate\n")
	sb.WriteString("   */\n")
	sb.WriteString("  invalidateCache(key: string): void;\n\n")

	sb.WriteString("  /**\n")
	sb.WriteString("   * Invalidate all cache entries.\n")
	sb.WriteString("   */\n")
	sb.WriteString("  invalidateAllCache(): void;\n\n")

	for _, svc := range services {
		sb.WriteString(fmt.Sprintf("  create%sClient(callerId: number): %s;\n", svc.Name.Name, svc.Name.Name))
	}

	sb.WriteString("}\n\n")
}

func (g *TypeScriptGenerator) generateGlobalDeclaration(sb *strings.Builder) {
	sb.WriteString("// Global declaration for browser environment\n")
	sb.WriteString("declare global {\n")
	sb.WriteString("  interface Window {\n")
	sb.WriteString("    ella: Ella;\n")
	sb.WriteString("  }\n")
	sb.WriteString("  const ella: Ella;\n")
	sb.WriteString("}\n\n")
	sb.WriteString("// Event fired when Ella WASM is ready\n")
	sb.WriteString("export type EllaReadyEvent = CustomEvent<void>;\n")
	sb.WriteString("export declare const ELLA_READY_EVENT: \"ellaReady\";\n")
}

func tsToCamelCase(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}
